### ISSUE TITLE
Cannot Import 'safe_join' from 'flask.helpers'

### ISSUE THREAD

**Issue by wakaru44** [pbatey/flask-staticdirs#1]
There is an ImportError while running 'flask run', using Flask==2.2.2.

`ImportError: cannot import name 'safe_join' from 'flask.helpers' (/env/lib/python3.9/site-packages/flask/helpers.py)`

safe_join was removed from flask.helpers in flask version 2.1.0 released on 28-03-2022

From flask [Version 2.1.0 CHANGES.rst](https://github.com/pallets/flask/blob/cb4f7425435c39a85c3ed17e395677597d9aaf31/CHANGES.rst#version-210)

> safe_join is removed, use werkzeug.utils.safe_join instead.

I solved the issue downgrading flask.

I also opened the issue about the same topic on [flask-api-example](https://github.com/pbatey/flask-api-example/issues/1). please close the one that is not relevant.

**Comment by pbatey** [comment]
Thanks for pointing this out!

This is now fixed and available in [v1.0.1](https://pypi.org/project/flask-staticdirs/1.0.1/).
